__version__ = '1.0.1'
__author__ = 'Jan Markowski'
__email__ = 'jan' '@' 'markowski.ca'
__url__ = 'https://github.com/jmarkowski/simple-todo-script'
__description__ = 'Super simple CLI todo script to track your list todos'
